name: Setup SOPS
author: nhedger
description: Setup SOPS in GitHub Actions
branding:
  color: gray-dark
  icon: lock
inputs:
  version:
    description: The version of SOPS to install
    required: true
    default: latest
runs:
  using: 'node16'
  main: 'dist/index.mjs'
